"""Layer-3 retrieval documents generated from the database (never hand-written).

Each document is a small, self-contained, numeric text with topic tags, e.g.
"Curry 2015-16 regular season", "Curry playoff shooting", "Curry clutch situations".
"""
from __future__ import annotations

from collections import defaultdict

from ..derive.aggregates import game_log_summary, num, season_lines
from .fmt import n, pct, season_line, signed


def _doc(slug, key, title, topics, text, season=None):
    return {"doc_key": f"{slug}:{key}", "title": title, "topics": sorted(set(topics)), "season": season, "text": text}


def build_documents(ds: dict, derived: dict) -> list:
    p = ds["player"]
    slug, name = p["slug"], p["full_name"]
    docs = []
    peak = {x["season"]: x["peak_score"] for x in derived.get("peak_scores", [])}
    ach_by_season = defaultdict(list)
    for a in ds.get("achievements", []):
        if a.get("season") and not a["achievement_type"].endswith("VOTING_FINISH"):
            ach_by_season[a["season"]].append(a["achievement_type"])

    for st in ("regular_season", "playoffs"):
        for l in season_lines(ds, st):
            sh, pbp, pp = l.get("shooting") or {}, l.get("pbp") or {}, l.get("per_poss") or {}
            lines = [f"{name} — {l['season']} {st.replace('_', ' ')} (source: {l['provenance'].get('source')}, {l['provenance'].get('source_url')})",
                     season_line(l, peak.get(l["season"]) if st == "regular_season" else None)]
            adv = l.get("advanced") or {}
            lines.append(f"Advanced: PER {n(adv.get('per'))}, OBPM {signed(adv.get('obpm'))}, DBPM {signed(adv.get('dbpm'))}, "
                         f"OWS {n(adv.get('ows'))}, DWS {n(adv.get('dws'))}, VORP {n(adv.get('vorp'))}, TOV% {pct(adv.get('tov_pct'))}, "
                         f"TRB% {pct(adv.get('trb_pct'))}, STL% {pct(adv.get('stl_pct'))}, BLK% {pct(adv.get('blk_pct'))}, "
                         f"3PA rate {n(adv.get('fg3a_rate'), 3)}, FTA rate {n(adv.get('fta_rate'), 3)}, ORtg {n(pp.get('ortg'), 0)}, DRtg {n(pp.get('drtg'), 0)}")
            topics = ["season", f"season:{l['season']}", st, "scoring", "efficiency"]
            if sh:
                lines.append(f"Shot profile: avg distance {n(sh.get('avg_shot_distance_ft'))} ft; share of FGA 0-3 ft {pct(sh.get('fga_share_0_3'))} "
                             f"(FG {pct(sh.get('fg_pct_0_3'))}), 3-10 ft {pct(sh.get('fga_share_3_10'))} (FG {pct(sh.get('fg_pct_3_10'))}), "
                             f"10-16 ft {pct(sh.get('fga_share_10_16'))} (FG {pct(sh.get('fg_pct_10_16'))}), 16 ft-3P {pct(sh.get('fga_share_16_3p'))} "
                             f"(FG {pct(sh.get('fg_pct_16_3p'))}), 3P {pct(sh.get('fga_share_3p'))} (FG {pct(sh.get('fg_pct_3p'))}); "
                             f"assisted: 2P {pct(sh.get('assisted_share_2p'))}, 3P {pct(sh.get('assisted_share_3p'))}; "
                             f"corner 3s {pct(sh.get('corner3_share_of_3pa'))} of 3PA at {pct(sh.get('corner3_fg_pct'))}; dunks {n(sh.get('dunks'))}")
                topics += ["shot-profile", "midrange", "rim", "three-point", "shot-creation"]
            if pbp:
                lines.append(f"Play-by-play: position est. PG {pct(pbp.get('pos_pg_share'), 0)} SG {pct(pbp.get('pos_sg_share'), 0)} "
                             f"SF {pct(pbp.get('pos_sf_share'), 0)} PF {pct(pbp.get('pos_pf_share'), 0)} C {pct(pbp.get('pos_c_share'), 0)}; "
                             f"on-court +/- per 100 {signed(pbp.get('on_court_pm_per100'))}, on-off {signed(pbp.get('on_off_pm_per100'))}; "
                             f"shooting fouls drawn {n(pbp.get('drawn_shooting'))}, and-1s {n(pbp.get('and1'))}, "
                             f"points generated by assists {n(pbp.get('points_generated_by_assists'))}, bad-pass TOV {n(pbp.get('tov_bad_pass'))}, "
                             f"lost-ball TOV {n(pbp.get('tov_lost_ball'))}")
                topics += ["positions", "playmaking", "foul-drawing", "turnovers"]
            if ach_by_season.get(l["season"]) and st == "regular_season":
                lines.append("Recognition this season: " + ", ".join(sorted(ach_by_season[l["season"]])))
                topics.append("awards")
            docs.append(_doc(slug, f"{st}:{l['season']}", f"{name} {l['season']} {st.replace('_', ' ')}", topics,
                             "\n".join(lines), l["season"]))

    # Finals / conference finals series
    for fs in derived.get("finals_series", []):
        sh = fs.get("shooting") or {}
        pg = fs.get("per_game") or {}
        txt = (f"{name} — {fs['season']} {fs['playoff_round'].replace('_', ' ')} vs {fs.get('opponent')} "
               f"(round label confidence: {fs.get('round_confidence')}; from game logs)\n"
               f"{fs['games']} games, record {fs.get('wins')}-{fs.get('losses')}: PTS {n(pg.get('pts_per_g'))}, TRB {n(pg.get('trb_per_g'))}, "
               f"AST {n(pg.get('ast_per_g'))}, TOV {n(pg.get('tov_per_g'))}, MP {n(pg.get('mp_per_g'))}, FG {pct(sh.get('fg_pct'))}, "
               f"3P {pct(sh.get('fg3_pct'))}, FT {pct(sh.get('ft_pct'))}, TS {pct(sh.get('ts_pct'))}")
        docs.append(_doc(slug, f"{fs['playoff_round']}:{fs['season']}", f"{name} {fs['season']} {fs['playoff_round'].replace('_', ' ')}",
                         ["playoffs", "finals" if fs["playoff_round"] == "nba_finals" else "conference-finals", "playoff-scoring",
                          "pressure", f"season:{fs['season']}"], txt, fs["season"]))

    agg = derived.get("aggregates", {})
    # Playoff career shooting
    po = agg.get("playoffs") or {}
    rs = agg.get("regular_season") or {}
    if po.get("totals"):
        txt = (f"{name} — career playoff vs regular-season shooting\n"
               f"Playoffs: {po['totals'].get('g')} G, PTS {n(po['per_game'].get('pts_per_g'))}, FG {pct(po['shooting'].get('fg_pct'))}, "
               f"3P {pct(po['shooting'].get('fg3_pct'))}, FT {pct(po['shooting'].get('ft_pct'))}, TS {pct(po['shooting'].get('ts_pct'))}, "
               f"USG {pct(po['advanced'].get('usg_pct'))}, BPM {signed(po['advanced'].get('bpm'))}\n"
               f"Regular season: TS {pct(rs.get('shooting', {}).get('ts_pct'))}, USG {pct(rs.get('advanced', {}).get('usg_pct'))}, "
               f"BPM {signed(rs.get('advanced', {}).get('bpm'))}")
        docs.append(_doc(slug, "playoff-shooting", f"{name} playoff shooting", ["playoffs", "playoff-scoring", "efficiency", "pressure", "shooting"], txt))

    # Clutch
    cl = (derived.get("features") or {}).get("clutch")
    if cl:
        txt = (f"{name} — clutch situations ({cl.get('definition')}; NBA.com, seasons {cl['seasons'][0]}..{cl['seasons'][-1]})\n"
               f"{n(cl.get('gp'), 0)} games, {n(cl.get('minutes'))} clutch minutes, {n(cl.get('pts'), 0)} pts ({n(cl.get('pts_per36'))} per 36), "
               f"FG {pct(cl.get('fg_pct'))} on {n(cl.get('fga'), 0)} FGA, 3P {n(cl.get('fg3m'), 0)}/{n(cl.get('fg3a'), 0)}, "
               f"FT {n(cl.get('ftm'), 0)}/{n(cl.get('fta'), 0)}, TS {pct(cl.get('ts_pct'))}, AST {n(cl.get('ast'), 0)}, TOV {n(cl.get('tov'), 0)}, "
               f"+/- {signed(cl.get('plus_minus'))}")
        docs.append(_doc(slug, "clutch", f"{name} clutch situations", ["clutch", "late-game", "final-shot", "pressure"], txt))
    else:
        docs.append(_doc(slug, "clutch", f"{name} clutch situations", ["clutch", "late-game", "final-shot"],
                         f"{name} — clutch situations: no clutch split data is stored for this player "
                         f"(NBA.com clutch splits start in 1996-97 and were not ingested). Do not infer clutch statistics."))

    # Play types per season
    pt_by = defaultdict(list)
    for r in ds.get("play_types", []):
        pt_by[(r["season"], r["stat_type"])].append(r)
    for (season, st), rows in sorted(pt_by.items()):
        body = "; ".join(f"{r['play_type']} freq {pct(r.get('frequency'))}, {n(r.get('ppp'), 2)} PPP, pct-ile {n(r.get('percentile'), 2)}"
                         for r in sorted(rows, key=lambda r: -(r.get("frequency") or 0)))
        docs.append(_doc(slug, f"playtypes:{st}:{season}", f"{name} {season} {st.replace('_', ' ')} play types",
                         ["play-types", "isolation", "pick-and-roll", "post", "transition", "off-ball", "spot-up", f"season:{season}"],
                         f"{name} — Synergy play types {season} {st.replace('_', ' ')} (NBA.com): {body}", season))
    # Tracking
    tr_by = defaultdict(list)
    for r in ds.get("tracking_shots", []):
        tr_by[(r["season"], r["stat_type"])].append(r)
    for (season, st), rows in sorted(tr_by.items()):
        body = "; ".join(f"{r['category']}:{r['label']} {pct(r.get('fga_frequency'))} of FGA, eFG {pct(r.get('efg_pct'))}" for r in rows)
        docs.append(_doc(slug, f"tracking:{st}:{season}", f"{name} {season} shot tracking",
                         ["tracking", "pull-up", "catch-and-shoot", "late-clock", "shot-creation", f"season:{season}"],
                         f"{name} — shot tracking {season} {st.replace('_', ' ')} (NBA.com): {body}", season))

    # Close games (final margin <= 3) from game logs — explicitly NOT clutch possessions
    for st in ("regular_season", "playoffs"):
        close = [g for g in ds.get("game_logs", []) if g["stat_type"] == st and g.get("margin") is not None and abs(g["margin"]) <= 3]
        if close:
            s = game_log_summary(close)
            txt = (f"{name} — {st.replace('_', ' ')} games decided by 3 points or fewer (full-game box scores, not late-game possessions)\n"
                   f"{s['games']} games, record {s['wins']}-{s['losses']}: PTS {n(s['per_game'].get('pts_per_g'))}, "
                   f"FG {pct(s['shooting'].get('fg_pct'))}, 3P {pct(s['shooting'].get('fg3_pct'))}, TS {pct(s['shooting'].get('ts_pct'))}, "
                   f"AST {n(s['per_game'].get('ast_per_g'))}, TOV {n(s['per_game'].get('tov_per_g'))}")
            docs.append(_doc(slug, f"close-games:{st}", f"{name} close games ({st.replace('_', ' ')})",
                             ["close-games", "late-game", "final-shot", "pressure", st], txt))
    # Top scoring games
    for st in ("regular_season", "playoffs"):
        games = [g for g in ds.get("game_logs", []) if g["stat_type"] == st and g.get("status") == "played" and g.get("stats")]
        if games:
            top = sorted(games, key=lambda g: -(num(g["stats"].get("pts")) or 0))[:8]
            body = "; ".join(f"{g['date']} vs {g['opponent']} {g['stats'].get('pts')} pts ({g['stats'].get('fg')}-{g['stats'].get('fga')} FG, "
                             f"{g['stats'].get('fg3')}-{g['stats'].get('fg3a')} 3P) {g.get('result') or ''}" for g in top)
            docs.append(_doc(slug, f"top-games:{st}", f"{name} top scoring games ({st.replace('_', ' ')})",
                             ["scoring", "game-highs", st], f"{name} — highest-scoring {st.replace('_', ' ')} games: {body}"))
    # Career-level topical docs
    f = derived.get("features") or {}
    docs.append(_doc(slug, "playmaking", f"{name} playmaking profile", ["playmaking", "usage", "turnovers", "pick-and-roll", "initiator"],
                     f"{name} — playmaking: career AST% {pct(f.get('ast_pct'))}, AST/G {n(f.get('ast_per_g'))}, TOV% {pct(f.get('tov_pct'))}, "
                     f"USG% {pct(f.get('usg_pct'))}, playoff AST% {pct(f.get('playoff_ast_pct'))}, playoff TOV% {pct(f.get('playoff_tov_pct'))}; "
                     f"career assists/turnovers {n(rs.get('shooting', {}).get('ast_to_tov'), 2)}"))
    docs.append(_doc(slug, "defense", f"{name} defensive profile", ["defense", "steals", "blocks", "rebounding"],
                     f"{name} — defense: STL% {pct(f.get('stl_pct'))}, BLK% {pct(f.get('blk_pct'))}, DRB% {pct(f.get('drb_pct'))}, "
                     f"DBPM {signed(f.get('dbpm'))}, All-Defensive selections {f.get('all_defensive_selections', 0)}, "
                     f"DPOY awards {f.get('award_counts', {}).get('DEFENSIVE_PLAYER_OF_THE_YEAR', 0)}"))
    sps = derived.get("shot_profile_summary") or {}
    docs.append(_doc(slug, "shot-creation", f"{name} shot creation and shot profile",
                     ["shot-creation", "isolation", "pull-up", "midrange", "rim", "three-point", "final-shot", "self-creation", "mismatch"],
                     f"{name} — career shot profile ({sps.get('coverage_note')}): rim {pct(sps.get('rim_frequency'))} of FGA "
                     f"(FG {pct(sps.get('rim_fg_pct'))}), 3-10 ft {pct(sps.get('short_midrange_frequency'))}, 10 ft-3P {pct(sps.get('midrange_frequency'))} "
                     f"(FG {pct(sps.get('midrange_fg_pct'))}), threes {pct(sps.get('three_point_frequency'))}, share of made 2s assisted "
                     f"{pct(sps.get('assisted_share_2p'))}, made 3s assisted {pct(sps.get('assisted_share_3p'))}; pull-up share {pct(sps.get('pull_up_frequency'))}, "
                     f"catch-and-shoot {pct(sps.get('catch_and_shoot_frequency'))}, isolation freq {pct(sps.get('isolation_frequency'))}, "
                     f"post-up freq {pct(sps.get('post_up_frequency'))}, late-clock {pct(sps.get('late_clock_frequency'))}; "
                     f"FTA per 36 {n(f.get('fta_per36'))}; listed height {p.get('height_in')} in."))
    return docs
